## 机器学习常用程式

### 线性代数（$Linear Algebra$）
涉及向量与矩阵等线性代数内容

In [ ]:
# 生成零向量
def generate_zero_vector(n: int) -> list[int|float]:
	return np.zeros(n)

In [ ]:
# 生成单位矩阵
def generate_identity_matrix(n: int) -> list[list[int|float]]:
	return np.identity(n)

In [ ]:
# 生成对角矩阵
def generate_matrix1(nums: List[int|float]) -> list[list[int|float]]:
	return np.diag(nums)

In [ ]:
# 向量点积
import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	x, y = np.array(a), np.array(b)
    try:
        ans = np.dot(x,y)
        return ans
    except:
        return -1

In [ ]:
# 向量转置
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
	return np.transpose(a)	# np.array(a).T	# 矩阵转置

In [ ]:
# 矩阵重构
def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
    try:
	    reshaped_matrix = np.reshape(a, new_shape)
	    return reshaped_matrix
    except:
        return [[]]

In [ ]:
# 计算矩阵均值
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
	dict = {"row": 1, "column": 0}
  ans = np.mean(np.array(matrix), axis=dict[mode])  # axis选择按行或列相加
  return np.around(ans, 1)  # 保留小数位数

In [ ]:
# 矩阵乘数
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	return np.multiply(np.array(matrix), scalar)

In [ ]:
# 矩阵乘法
def matrix_multiply(a: list[list[int|float]], b: list[list[int|float]]) -> list[list[int|float]]:
	return np.matmul(np.array(a), np.array(b))  # 或者 return a@b

In [ ]:
# 矩阵模
def cal_norm(a: np.ndarray) -> float:
  return np.linalg.norm(a)

#### 特征值：
+ 先回忆特征值的定义：（$\textbf{A}$为矩阵，$v$为特征向量）
$$
\textbf{A}v=\lambda v
$$
+ 回忆计算方式：
$$
  (\textbf{A}-\lambda)v\Rightarrow (\textbf{A}-\lambda\textbf{E})v=\textbf{0}\\
  v\neq\textbf{0}\Rightarrow \textbf{A}-\lambda\textbf{E}=\textbf{0}\\
  \therefore |\textbf{A}-\lambda\textbf{E}|=0
$$

In [ ]:
# 求特征值与特征向量
def calculate_eigenvalues(matrix: list[list[float|int]]) -> list[float]:
	eigenvalues, figturevectors = np.linalg.eig(np.array(matrix))
  return eigenvalues, figturevectors

In [ ]:
# 矩阵求逆
def matrix_inverse(matrix: list[list[float|int]]) -> list[list[float|int]]:
  return np.linalg.inv(np.array(matrix))

#### `Jacobi`（迭代法）解线性方程
+ 迭代法：一种不断用变量旧值递推新值，逐渐逼近解值的方法（收敛）
+ 推导：
  + $\textbf{A}\overrightarrow{x}=\overrightarrow{b}$的解可以如下表示（$a_{ii}\neq 0$）：
$$
\begin{align*}
\begin{pmatrix}
a_{11}&a_{12}&a_{13}\\
a_{21}&a_{22}&a_{23}\\
a_{31}&a_{32}&a_{33}
\end{pmatrix}
\cdot
\begin{pmatrix}
x_1\\
x_2\\
x_3
\end{pmatrix}
=
\begin{pmatrix}
b_1\\
b_2\\
b_3
\end{pmatrix}⇒
\begin{cases}
x_1=\frac{1}{a_{11}}(-a_{12}x_2-...-a_{1n}x_n+b_1)\\
...\\
x_i=\frac{1}{a_{ii}}(-a_{i1}x_1-...-a_{i,i-1}x_{i-1}-...a_{i,n}x_n+b_i)
\end{cases}\\
\\
Set\space b_{ij}=a_{ij}/a_{ii},(i\neq j),g_i=b_i/a_{ii}
⇒
\begin{cases}
x_1=b_{12}x_2+b_{13}x_3+...+b_{1n}x_n+g_1\\
...\\
x_n=b_{n1}x_1+b_{n2}x_2+...+b_{n,n-1}x_{n-1}+g_n
\end{cases}\\
\newline
Then\space set\space\textbf{B}=
\begin{pmatrix}
0&b_{12}&b_{13}&...&b_{1n}\\
b_{21}&0&b_{23}&...&b_{2n}\\
...&...&...& &...\\
b_{n1}&b_{n2}&b_{n3}&...&0
\end{pmatrix}
⇒\overrightarrow{x}=\textbf{B}\overrightarrow{x}+\overrightarrow{g}\\
\\
Then\space set\space
\textbf{D}=
\begin{pmatrix}
a_{11}& & & \\
 &a_{22}& & \\
 & &...& \\
 & & &a_{nn}
\end{pmatrix}\\
⇒ \textbf{B}=\textbf{D}^{-1}(\textbf{D}-\textbf{A})
=\textbf{E}-\textbf{D}^{-1}\textbf{A},\space\overrightarrow{g}=\textbf{D}^{-1}\overrightarrow{b}\\
\\
\therefore If\space \overline{x}=(\textbf{E}-\textbf{B})\overline{x}=\overrightarrow{b},\space then\space\overline{x}\space is\space solution.
\end{align*}
$$

In [ ]:
# jacobi迭代n次
def solve_jacobi(A: np.ndarray, b: np.ndarray, n: int) -> list:
    dim = len(b)
    x, t = np.zeros(dim), np.zeros(dim)

    inv_D = np.diag([1 / A[i][i] for i in range(dim)])

    for _ in range(n):
        x = t - inv_D @ A @ t + inv_D @ b
        t = x.copy()
    return t

#### $Laplace$ 定理求行列式

**粗體文字**#### 奇异值分解$SVD$
+ SVD 分解的分类：
  + 全SVD：对任意实矩阵 $A_{m\times n}$（秩为r），可分解为：
$$
A=U_{m×m}Σ_{m×n}V^T_{n×n}
$$
    其中：
    + $U$ 为 $m×m$ 的正交矩阵（列向量两两正交，且单位化，$U^TU=E$），其列向量称为 $A$ 的左奇异向量
    + $Σ$ 为 $m×n$ 的对角矩阵，对角元素为 $A$ 的奇异值 $σ_q\geq σ_2\geq...\geqσ_r>0$（即：$Σ=diag(σ_1,...,σ_r,0,...,0)$）
    + $V$ 为 $n×n$ 的正交矩阵，其列向量称为 $A$ 的右奇异向量
  
  + 降阶SVD：简化的分解形式（秩为r）
$$
A=U_{m×r}Σ_{r×r}V^T_{n×r}
$$
    其中
    + $U_{m×r}$ 前r列对应非零奇异值的左奇异向量
    + $Σ_{r×r}$ 前r个非零奇异值构成对角阵 $diag(σ_1,...,σ_r)$
    + $V_{n×r}$ 前r列对应非零奇异值的右奇异向量

+ 求解SVD分解：
  + 正交矩阵 $AA^T=E\Rightarrow A^{-1}=A^T$
  + 矩阵转置 $(UV^T)^T=VU^T$
  + 对角阵 $A=A^T$

    得到：
$$
AA^T=(UΣV^T)(UΣV^T)^T=UΣV^TVΣ^TU^T=UΣ^2U^T\\
A^TA=(UΣV^T)^T(UΣV^T)=VΣ^TU^TUΣV^T=VΣ^2V^T
$$

    而 $A=UBU^T$ 这种结构与`施密特正交化`以及`相似矩阵`都有巨大联系，这都与矩阵的**特征值**和**特征向量**密不可分。

    事实上，这两部分刚好构成了我们所需的 $U$ 和 $V$。
    
    由于，特征值特征向量求解涉及多项式求解问题，对于低维矩阵是存在快速分解方式的。

  + $Jacobi$ 旋转：
    + 用于对称矩阵对角化，通过一系列的平面旋转来消除非对角项：
      
      对于2×2的实对称矩阵：
$$
M=
\begin{pmatrix}
a&b\\
b&c
\end{pmatrix}
$$
      可以通过一个旋转矩阵R(θ)：
$$
R(θ)=
\begin{pmatrix}
\cosθ&-\sinθ\\
\sinθ&\cosθ
\end{pmatrix}
$$
      对其进行相似变换：
$$
R^TMR
$$
      得到近似对角形式（通过旋转使得`b`接近于0）
    + 推导旋转角度θ：
    
      旋转角度通过以下公式导出：
$$
τ=\frac{c-a}{2b},\space t=\frac{sign(τ)}{|τ|+\sqrt{1+τ^2}}
$$
      然后得到：
$$
\cosθ=\frac{1}{\sqrt{1+t^2}},\space\sinθ=t⋅\cosθ
$$

In [2]:
import numpy as np
import math

def svd_2x2_singular_values(A: np.ndarray):
  a2 = A.T @ A
  v = np.eye(2)

  # 进行1次Jacobi旋转
  for _ in range(1):
    if a2[0,0] == a2[1,1]:
      theta = np.pi/4
    else:
      # arctan(2b/(c-a))
      theta = np.arctan2(2 * a2[0,1], a2[0,0] - a2[1,1]) / 2

    # 旋转矩阵
    r = np.array([
      [np.cos(theta), -np.sin(theta)],
      [np.sin(theta), np.cos(theta)]
    ])
    d = np.transpose(r) @ a2 @ r  # d=r^Ta^Tar=(ar)^Tar
    a2 = d
    v = v @ r # !!

  # 计算sigma
  s = np.sqrt([d[0,0], d[1,1]])
  s_inv = np.array([[1/s[0], 0], [0, 1/s[1]]])

  u = a @ v @ s_inv # usv^Tvs_inv=u
  return (u, s, v.T)

a = np.array([[2, 1], [1, 2]])
svd_2x2_singular_values(a)

(array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

  + SVD分解的几何意义：
$$
A=UΣV^T
$$
    其中：
    + $U$为正交矩阵（左奇异向量），定义了对输出空间的正交基
    + $Σ$为对角矩阵，包含奇异值（表示伸缩因子）
    + $V^T$为正交矩阵（右奇异向量转置），定义了对输入空间的正交基

    比如：
$$
Ax=UΣV^Tx
$$
    + $V^T$将$x$旋转到某个方向
    + $Σ$对这两个方向进行伸缩
    + $U$将该向量旋转到输出空间方向

### 统计学（$Statics$）
涉及概率论等内容：

#### 协方差
+ 方差：用于刻画一组（列）数据离散程度
  + 总体方差：$Var(x)=\frac{1}{n}\sum^n_{i=1}(x_i-\mu)^2$
  + 样本方差：$S^2(x)=\frac{1}{n-1}\sum^n_{i=1}(x_i-\overline{x})^2$，（$\frac{1}{n-1}$ 是为了无偏估计）

    样本均值：$\overline{x}=\frac{1}{n}\sum^n_{i=1}x_i$
+ 协方差：刻画多组（列）数据之间的相关程度
  + 总体协方差：$cov(x,y)=\frac{1}{n}\sum^n_{i=1}(x_i-\mu_x)(y_i-\mu_y)$
  + 样本协方差：$S(x,y)=\frac{1}{n-1}\sum^n_{i=1}(x_i-\overline{x})(y_i-\overline{y})$

+ 均值归零化（中心化）：$a_i=x_i-\overline{x},(i=1,2,...,n)$
  + 重要结论：
    + 每列均值变为0
    + 每列方差不变，不影响原数据分布
    + 协方差不变，不影响原有线性相关程度
    + 协方差数据不变，不影响数据与所有组相关程度
  + 求协方差：$S(x,y)=\frac{1}{n-1}\sum^n_{i=1}a_ib_i$

+ 协方差矩阵：刻画每组数据与所有组的相关程度
  + 基本算法：将归零化后的矩阵记作$X$，计算$\Sigma=\frac{1}{n-1}X^TX$
  + 性质：
    + 协方差矩阵是一个是对称矩阵
    + 协方差矩阵主对角线上的数值为每列（特征）数据的方差

In [ ]:
# 计算协方差矩阵
def calculate_covariance_matrix(vectors: list[list[float]]) -> list[list[float]]:
  # 检查是否每个特征的样本数相同
  if len(set(len(row) for row in data)) != 1:
      raise ValueError("All features must have the same number of observations.")
  return np.cov(np.array(vectors), bias=False)